name: Master Build

on:
  push:
    branches: [ master ]

#defaults:
#  run:
#    # Having a global working directory will not work when more projects are added
#    working-directory: ./CMR/python

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.4
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Version Info
        run:  |
          ver=$(grep version setup.py | sed -e 's/version=\"\(.*\)\",/\1/g')
          sed -i'' -e "s/\"{BUILD_VERSION}\"/\"${ver}\"/g' cmr/__init__.py
          sed -i'' -e 's/"{BUILD_REF}"/"${{ github.ref }}"/g' cmr/__init__.py
          sed -i'' -e "s/\"{BUILD_DATE}\"/\"$(date)\"/g" cmr/__init__.py
      - name: Run Unit Tests
        run: python3 -m unittest discover
        working-directory: ./CMR/python
      - name: Lint
        run: ./runme.sh -l
        working-directory: ./CMR/python
      - name: Package
        run: python3 setup.py sdist bdist_wheel
        working-directory: ./CMR/python
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: CMR/python/dist/eo_metadata_tools_cmr-*-py3-none-any.whl
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-master"
          prerelease: true
          title: "Master Build"
          files: CMR/python/dist/eo_metadata_tools_cmr-*-py3-none-any.whl
