name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#defaults:
#  run:
#    # Having a global working directory will not work when more projects are added
#    working-directory: ./CMR/python

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          pip3 install coverage
          coverage run -m unittest discover
        working-directory: ./CMR/python
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: ./.coverage
          directory: ./CMR/python/
      - name: Lint
        run: ./runme.sh -l
        working-directory: ./CMR/python
